import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { socket } from '../socket';
import { LogOut, Swords, Trophy, Activity, Plus, LogIn, Calendar, User } from 'lucide-react';

const Dashboard = ({ onCreateRoom, onJoinRoom }) => {
  const { user, logout, fetchProfile } = useAuth();
  const [profileData, setProfileData] = useState(null);
  const [roomCode, setRoomCode] = useState('');
  const [joinError, setJoinError] = useState('');
  const [loadingProfile, setLoadingProfile] = useState(true);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedTime, setSelectedTime] = useState(10);
  const [selectedColor, setSelectedColor] = useState('random');

  useEffect(() => {
    let active = true;
    const loadProfile = async () => {
      try {
        const data = await fetchProfile();
        if (active) {
          setProfileData(data);
          setLoadingProfile(false);
        }
      } catch (err) {
        console.error(err);
      }
    };
    loadProfile();
    return () => { active = false; };
  }, []);

  const handleCreateGame = () => {
    setShowCreateModal(true);
  };

  const handleConfirmCreate = () => {
    setShowCreateModal(false);
    if (!socket.connected) socket.connect();
    socket.emit('create-room', { 
      userId: user.id, 
      username: user.username,
      timeLimit: selectedTime,
      preferredColor: selectedColor
    });
    
    socket.once('room-created', ({ roomId, color }) => {
      onCreateRoom(roomId, color);
    });
  };

  const handleJoinGame = (e) => {
    e.preventDefault();
    setJoinError('');
    if (!roomCode || roomCode.trim().length !== 6) {
      setJoinError('Please enter a valid 6-digit room code.');
      return;
    }

    if (!socket.connected) socket.connect();
    socket.emit('join-room', { 
      roomId: roomCode.trim(), 
      userId: user.id, 
      username: user.username 
    });

    socket.once('room-joined', ({ roomId, color }) => {
      onJoinRoom(roomId, color);
    });

    socket.once('join-error', ({ message }) => {
      setJoinError(message);
    });
  };

  const formatDate = (dateString) => {
    const options = { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' };
    return new Date(dateString).toLocaleDateString(undefined, options);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', width: '100%' }}>
      {/* Header bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 className="title-gradient" style={{ fontSize: '2rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Swords style={{ width: '32px', height: '32px', stroke: '#66fcf1' }} />
            Spell Chess
          </h2>
          <p style={{ color: 'var(--text-muted)' }}>Welcome back, {user?.username}!</p>
        </div>
        <button className="btn-secondary" onClick={logout} style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <LogOut size={16} /> Logout
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '2rem', alignBreak: 'start' }} className="game-grid">
        {/* Play panel */}
        <div className="glass-panel" style={{ padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <h3 style={{ borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem', color: 'var(--primary-neon)' }}>Matchmaking</h3>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <div>
              <p style={{ marginBottom: '0.8rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>Create a new match lobby and share the room code with a friend.</p>
              <button className="btn-primary" onClick={handleCreateGame} style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
                <Plus size={18} /> Create Game Room
              </button>
            </div>

            <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1.5rem' }}>
              <p style={{ marginBottom: '0.8rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>Enter a room code generated by your friend to join their game.</p>
              <form onSubmit={handleJoinGame} style={{ display: 'flex', gap: '10px' }}>
                <input 
                  type="text" 
                  className="input-field" 
                  placeholder="6-Digit Room Code"
                  maxLength={6}
                  value={roomCode}
                  onChange={(e) => setRoomCode(e.target.value.replace(/\D/g, ''))}
                  style={{ textAlign: 'center', fontSize: '1.2rem', letterSpacing: '4px', fontWeight: 'bold' }}
                />
                <button type="submit" className="btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap' }}>
                  <LogIn size={18} /> Join Game
                </button>
              </form>
              {joinError && <p style={{ color: 'var(--accent-pink)', fontSize: '0.85rem', marginTop: '0.5rem' }}>{joinError}</p>}
            </div>
          </div>
        </div>

        {/* Profile Stats & History */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {loadingProfile ? (
            <div className="glass-panel" style={{ padding: '2rem', textAlign: 'center' }}>Loading user stats...</div>
          ) : (
            <>
              {/* User Stats Card */}
              <div className="glass-panel" style={{ padding: '2rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '1.5rem' }}>
                  <User style={{ stroke: 'var(--primary-neon)' }} />
                  <h3 style={{ color: 'var(--primary-neon)' }}>Player Profile</h3>
                </div>
                
                <div className="stats-grid">
                  <div className="stat-box">
                    <div className="stat-value">{profileData?.stats?.totalMatches}</div>
                    <div className="stat-label">Played</div>
                  </div>
                  <div className="stat-box" style={{ borderLeft: '2px solid rgba(102, 252, 241, 0.1)' }}>
                    <div className="stat-value" style={{ color: '#00e676' }}>{profileData?.stats?.wins}</div>
                    <div className="stat-label">Wins</div>
                  </div>
                  <div className="stat-box" style={{ borderLeft: '2px solid rgba(102, 252, 241, 0.1)' }}>
                    <div className="stat-value" style={{ color: 'var(--accent-pink)' }}>{profileData?.stats?.losses}</div>
                    <div className="stat-label">Losses</div>
                  </div>
                  <div className="stat-box" style={{ borderLeft: '2px solid rgba(102, 252, 241, 0.1)' }}>
                    <div className="stat-value" style={{ color: '#ffb300' }}>{profileData?.stats?.draws}</div>
                    <div className="stat-label">Draws</div>
                  </div>
                  <div className="stat-box" style={{ borderLeft: '2px solid rgba(102, 252, 241, 0.1)' }}>
                    <div className="stat-value">{profileData?.stats?.winRate}%</div>
                    <div className="stat-label">Win Rate</div>
                  </div>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1rem' }}>
                  <Calendar size={14} /> Registered: {profileData?.user?.created_at ? formatDate(profileData.user.created_at) : 'N/A'}
                </div>
              </div>

              {/* Match History Table */}
              <div className="glass-panel" style={{ padding: '2rem', overflowX: 'auto' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '1rem' }}>
                  <Trophy style={{ stroke: 'var(--primary-neon)' }} />
                  <h3 style={{ color: 'var(--primary-neon)' }}>Match History</h3>
                </div>

                {profileData?.matches?.length === 0 ? (
                  <p style={{ color: 'var(--text-muted)', textAlign: 'center', padding: '2rem' }}>No matches played yet. Start a new match to write your history!</p>
                ) : (
                  <table className="match-history-table">
                    <thead>
                      <tr>
                        <th>Players</th>
                        <th>Winner</th>
                        <th>Status</th>
                        <th>Ended</th>
                      </tr>
                    </thead>
                    <tbody>
                      {profileData?.matches?.map((match) => {
                        const isWinner = match.winner === user.username;
                        const isDraw = match.winner === 'Draw';
                        const isLoss = !isWinner && !isDraw;
                        
                        let winnerStyle = { color: 'white' };
                        if (isWinner) winnerStyle = { color: '#00e676', fontWeight: 'bold' };
                        else if (isLoss) winnerStyle = { color: 'var(--accent-pink)' };

                        return (
                          <tr key={match.id}>
                            <td>
                              <span style={{ color: 'var(--primary-neon)' }}>{match.whitePlayer}</span> (W) vs <span style={{ color: 'var(--secondary-neon)' }}>{match.blackPlayer}</span> (B)
                            </td>
                            <td style={winnerStyle}>{match.winner}</td>
                            <td style={{ textTransform: 'capitalize', fontSize: '0.85rem' }}>{match.status}</td>
                            <td style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{formatDate(match.endedAt)}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                )}
              </div>
            </>
          )}
        </div>
      </div>
      {/* Create Room Options Modal Dialog */}
      {showCreateModal && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(0, 0, 0, 0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000
        }}>
          <div className="glass-panel" style={{ padding: '2.5rem', maxWidth: '400px', width: '90%', display: 'flex', flexDirection: 'column', gap: '1.5rem', border: '2px solid var(--primary-neon)' }}>
            <h3 className="title-gradient" style={{ fontSize: '1.6rem', textAlign: 'center', marginBottom: '0.5rem' }}>Create Room</h3>
            
            {/* Time selection */}
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem', fontWeight: 'bold' }}>SELECT TIME LIMIT</label>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px' }}>
                {[5, 10, 30].map(time => (
                  <button
                    key={time}
                    type="button"
                    onClick={() => setSelectedTime(time)}
                    className={selectedTime === time ? 'btn-primary' : 'btn-secondary'}
                    style={{ padding: '10px 0', fontSize: '0.9rem' }}
                  >
                    {time} Min
                  </button>
                ))}
              </div>
            </div>

            {/* Color selection */}
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem', fontWeight: 'bold' }}>CHOOSE PIECE COLOR</label>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px' }}>
                {[
                  { value: 'w', label: 'White' },
                  { value: 'random', label: 'Random' },
                  { value: 'b', label: 'Black' }
                ].map(opt => (
                  <button
                    key={opt.value}
                    type="button"
                    onClick={() => setSelectedColor(opt.value)}
                    className={selectedColor === opt.value ? 'btn-primary' : 'btn-secondary'}
                    style={{ padding: '10px 0', fontSize: '0.9rem' }}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Action buttons */}
            <div style={{ display: 'flex', gap: '10px', marginTop: '1rem' }}>
              <button 
                type="button"
                className="btn-primary" 
                onClick={handleConfirmCreate}
                style={{ flex: 1, padding: '12px' }}
              >
                Create Room
              </button>
              <button 
                type="button"
                className="btn-secondary" 
                onClick={() => setShowCreateModal(false)}
                style={{ flex: 1, padding: '12px' }}
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;
